name: Deploy to VPS

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check network connection to VPS
        run: |
          echo "Pinging VPS_HOST..."
          ping -c 4 ${{ secrets.VPS_HOST }}
          echo "Testing port 22..."
          nc -zv ${{ secrets.VPS_HOST }} 22 || echo "Port 22 is unreachable from GitHub!"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /var/www/tasghor.rtsquad.com
            git config --global --add safe.directory /var/www/tasghor.rtsquad.com
            git fetch origin
            git checkout ${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}
            git clean -fd
